# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsTracker
#Firebase
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'

#GoogleLogin
pod 'GoogleSignIn'

end
